--by 风吹那啥凉 
if GetLocale() == "zhCN" then

	-- update needed msg
	TukuiL.option_update = "由于Tukui的上一次更新，你必须升级你的Tukui ConfigUI， 请访问 www.tukui.org"
	
	--Duffed
	TukuiL.option_general_blizzardsct = "Skin Blizzard SCT"
	TukuiL.option_general_normalfont = "Use the Normal/Old Font instead of pixelfont."
	TukuiL.option_general_overridehightolow = "Use Low-res Version on High-res"
	TukuiL.option_general_bordercolor = "Bordercolor (Tukui Panels)"
	TukuiL.option_general_backdropcolor = "Backdropcolor (Tukui Panels)"
	TukuiL.option_general_classcolored_border = "Tukui-Panel-Border classcolored"

	TukuiL.option_datatext_color = "Text Color (datatext, chat etc.)"
	TukuiL.option_datatext_classcolored = "Classcolored Text"
	TukuiL.option_datatext_zonepanel = "Panel that shows current Zone below Minimap"
	TukuiL.option_datatext_experience = "Experience Position"
	TukuiL.option_datatext_reputation = "Reputation Position"
	TukuiL.option_datatext_mmenu = "mMenu Position (mMenu required)"
	TukuiL.option_datatext_font = "Font (datatext, buffs, chat-tabs, ClassTimer)"
	TukuiL.option_datatext_honorablekills = "Honorable Kills Position"
	TukuiL.option_datatext_honor = "Honor Position"

	TukuiL.option_unitframes_healthbarcolor = "Healthbar Color (unicolor)"
	TukuiL.option_unitframes_deficitcolor = "Deficit Color (unicolor)"
	TukuiL.option_unitframes_priestarmor = "Display current Armor for Priest"
	TukuiL.option_unitframes_totandpetlines = "Display Lines from Pet & ToT"
	TukuiL.option_unitframes_framewidth = "Player & Target width (affect also boss- & arenaframes)"
	TukuiL.option_unitframes_fader = "[EXPERIMENTAL] Fade Unitframes out when not in combat (+ some more conditions ofc)"
	TukuiL.option_unitframes_faderalpha = "(Fader) Alpha for frames (if not 0)"
	TukuiL.option_unitframes_vengeancebar = "Display Vengeance-Bar instead of Threat-Bar"
	TukuiL.option_unitframes_largefocus = "Use larger Focus Frame"
	TukuiL.option_unitframes_gridvertical = "Grid direction vertical instead of horizontal"
	TukuiL.option_unitframes_gridpets = "Show pets in Grid Layout (only in group, not raid)"
	TukuiL.option_unitframes_fontsize = "Unitframe Fontsize"
	TukuiL.option_unitframes_gridsolo = "Show Grid even without a Group (Solo)"
	TukuiL.option_unitframes_focusdebuffs = "Enable Focus Debuffs"
	TukuiL.option_unitframes_buffrows = "Buff-rows above Target"
	TukuiL.option_unitframes_debuffrows = "Debuff-rows above Target"
	TukuiL.option_unitframes_portraitstyle = "Portrait Style: ICON or MODEL (Layout 2 only)"
	TukuiL.option_unitframes_layout = "Layout (1, 2, 3)"
	TukuiL.option_unitframes_colorgradient = "Add Color-Gradient to healthbar (from red to healthbarcolor u set in config)"
	TukuiL.option_unitframes_powerclasscolored = "Powerbar in class-color instead of power-color"
	TukuiL.option_unitframes_outline = "Set Outline for Unitframes (NONE, OUTLINE, THINOUTLINE)"
	TukuiL.option_unitframes_percent = "Show HP-Percent left an right of Player & Target"

	TukuiL.option_castbar = "Castbar"
	TukuiL.option_castbar_color = "Castbarcolor for not-player (if not classcolored)"
	TukuiL.option_castbar_classcolored = "Castbar classcolored."
	TukuiL.option_castbar_targetyoffset = "Target Castbar offset from the BOTTOM"
	TukuiL.option_castbar_targetxoffset = "Target Castbar offset from the CENTER (horizontal)"
	TukuiL.option_castbar_targetwidth = "Target Castbar width"
	TukuiL.option_castbar_focusyoffset = "Focus Castbar offset from the TOP"
	TukuiL.option_castbar_focusxoffset = "Focus Castbar offset from the CENTER (horizontal)"
	TukuiL.option_castbar_focuswidth = "Focus Castbar width"

	TukuiL.option_actionbar_swaprbar1and3 = "Swap Mainbar with 2. or 3. (depends on which AB-Layout you use)"
	TukuiL.option_actionbar_rightbarsmouseover = "Rightbars on mouseover"
	TukuiL.option_actionbar_shapeshiftborder = "Display Border around Shapeshiftbar"
	TukuiL.option_actionbar_shapeshiftmouseover = "Shapeshiftbar on mouseover"
	TukuiL.option_actionbar_shapeshiftvertical = "Set Shapeshiftbar vertical"
	TukuiL.option_actionbar_macrotext = "Display Macrotext"
	TukuiL.option_actionbar_macro = "Enable Macrohighlightning for Procs"
	TukuiL.option_actionbar_petbaralwaysvisible = "Always show Petbar even if rightbarsmouseover = true"
	TukuiL.option_actionbar_petbarhorizontal = "Petbar horizontal on top of Bar2/1"
	TukuiL.option_actionbar_button2 = "Show or Hide the +/-Button at the bottom Datatextpanel"
	TukuiL.option_actionbar_barlayout = "Set Actionbarlayout"
	TukuiL.option_actionbar_panels = "Show or Hide the Actionbarpanels (only if you use an alternative Actionbarmod)"

	TukuiL.option_duffed_drinkannouncement = "Announce 'drinking' in  Arena"
	TukuiL.option_duffed_ccannouncement = "Announce CC/Buffs/Debuffs"
	TukuiL.option_duffed_sayinterrupt = "Announce when you interrupt someone"
	TukuiL.option_duffed_dispelannouncement = "Announce Dispels"
	TukuiL.option_duffed_tbtimer = "Enable Tol Barad-Timer in watchframe"
	TukuiL.option_duffed_priest_sos = "Enable display for Strength of Soul (Priests only)"
	TukuiL.option_duffed_arenaonly = "Aura & Interrupt announcement in arena only."
	TukuiL.option_duffed_announcechannel = "Set channel for Announcement (SAY, GROUP, RAID)"

	TukuiL.option_classtimer = "Classtimer"
	TukuiL.option_classtimer_enable = "Enable Classtimer"
	TukuiL.option_classtimer_playercolor = "Player-Bar Color"
	TukuiL.option_classtimer_targetbuffcolor = "Target-Buffs Color"
	TukuiL.option_classtimer_targetdebuffcolor = "Target-Debuffs Color"
	TukuiL.option_classtimer_trinketcolor = "Player-Trinket(Procs) Color"
	TukuiL.option_classtimer_targetdebuffs = "Target Debuffs above Target (looks crappy imo :))"

	TukuiL.option_chat_addonborder = "Create Panel that looks exactly like the left chat (by default) at the BOTTOMRIGHT"
	TukuiL.option_chat_leftchatbackground = "Show Background for the left Chat (ChatFrame1)"
	TukuiL.option_chat_rightchatbackground = "Show Background for the right Chat (ChatFrame4)"
	TukuiL.option_chat_rightchatnumber = "Chat Number X (For Rightchat-Background)"
	TukuiL.option_chat_fading = "Enable fading"
	TukuiL.option_chat_rightchatalign = "Set textalign of right chat to left or right"

	TukuiL.option_skins = "Skins"
	TukuiL.option_skins_background = "Create Panel that looks exactly like the left chat (by default) at the BOTTOMRIGHT"
	TukuiL.option_skins_combat_toggle = "Toggle Addonbackground in-/outfight (NOTE: Turn off auto-hide functions in these Addons)"
	TukuiL.option_skins_bskins = "Enable Skinning for Blizzardframes"
	TukuiL.option_skins_itemborder =  "Enable Qualityborder for Items on Character / Inspectframe"

	TukuiL.option_misc = "Misc Options"
	TukuiL.option_misc_swingtimerenable = "Enable SwingTimer"
	TukuiL.option_misc_swingtimerwidth = "Swingtimer Width"
	TukuiL.option_misc_swingtimerheight = "Swingtimer Height"
	TukuiL.option_misc_swingtimercolor = "Swingtimer Bar-Color"
	TukuiL.option_misc_sesenable = "Enable Specswitcher"
	TukuiL.option_misc_sesenablegear = "Enable automatic gearswap"
	TukuiL.option_misc_sesset1 = "Equipset for first spec (must be a number between 1 - 10)"
	TukuiL.option_misc_sesset2 = "Equipset for second spec (must be a number between 1 - 10)"
	TukuiL.option_misc_sesgearswap = "Enable automatic gearswap for respec"
	TukuiL.option_misc_sescastbar = "Enable castbar for specswitcher"
	TukuiL.option_misc_rbf = "Enable RaidBuff Reminder"
	TukuiL.option_misc_rbfmouseover = "Enable mouseover for RaidBuff Reminder"
	TukuiL.option_misc_rbfvertical = "Set RaidBuff Reminder vertical"
	TukuiL.option_nameplate_debuff =  "Enable Debuffdisplay on nameplates"
	TukuiL.option_misc_tbchattab = "Set Threatbarpoint to ChatBG2Tab"
	TukuiL.option_misc_sComboenable = "Enable sCombo-Addon for combopoints instead of default cp-display"
	TukuiL.option_misc_sComboenergybar = "Show Energy-Bar below Combopoints"

	-- general
	TukuiL.option_general = "综合"
	TukuiL.option_general_uiscale = "自动UI缩放"
	TukuiL.option_general_override = "在低分辨率条件下使用高分辨率样式"
	TukuiL.option_general_multisample = "多重采样保护"
	TukuiL.option_general_customuiscale = "UI缩放 (自动缩放必须被禁用)"
	TukuiL.option_general_backdropcolor = "设置为默认面板背景颜色"
	TukuiL.option_general_bordercolor = "设置为默认边框颜色"
	TukuiL.option_general_blizzardreskin = "改变暴雪样式的框体为Tukui风格"
	
	-- nameplate
	TukuiL.option_nameplates = "姓名板"
	TukuiL.option_nameplates_enable = "开启姓名版"
	TukuiL.option_nameplates_enhancethreat = "启用仇恨着色模式，将会根据你的角色自动改变颜色"
	TukuiL.option_nameplates_showhealth = "在姓名板上显示生命值"
	TukuiL.option_nameplates_combat = "仅在战斗中显示姓名板"
	TukuiL.option_nameplates_goodcolor = "安全仇恨值颜色，取决于你是坦克还是治疗者"
	TukuiL.option_nameplates_badcolor = "危险仇恨值颜色，取决于你是治疗还是输出"
	TukuiL.option_nameplates_transitioncolor = "失去/获得仇恨值颜色"
	 
	-- merchant
	TukuiL.option_merchant = "商人"
	TukuiL.option_merchant_autosell = "自动售卖灰色物品"
	TukuiL.option_merchant_autorepair = "自动修理物品"
	TukuiL.option_merchant_sellmisc = "自动贩卖特定物品(非灰色等级的指定物品)"
	TukuiL.option_merchant_sellmisc = "Sell some defined (craps not grey) items automatically"
	TukuiL.option_merchant_autoguildrepair = "Autorepair from Guild Bank if possible."
	 
	-- bags
	TukuiL.option_bags = "背包"
	TukuiL.option_bags_enable = "开启背包整合"
	TukuiL.option_bags_moveable = "Enable to move your bags"
	TukuiL.option_bags_transparent = "Enable Transparent for bags"
	 
	-- datatext
	TukuiL.option_datatext = "信息文本"
	TukuiL.option_datatext_24h = "使用24小时制"
	TukuiL.option_datatext_localtime = "使用本地时间取代服务器时间"
	TukuiL.option_datatext_bg = "启用战场状态"
	TukuiL.option_datatext_hps = "每秒治疗(输入0关闭)"
	TukuiL.option_datatext_guild = "公会信息 (输入0关闭)"
	TukuiL.option_datatext_arp = "护甲穿透 (输入0关闭)"
	TukuiL.option_datatext_mem = "内存占用信息 (输入0关闭)"
	TukuiL.option_datatext_bags = "背包 (输入0关闭)"
	TukuiL.option_datatext_fontsize = "文本字体大小"
	TukuiL.option_datatext_fps_ms = "延时和帧数(输入0关闭)"
	TukuiL.option_datatext_armor = "护甲值 (输入0关闭)"
	TukuiL.option_datatext_avd = "躲闪 (输入0关闭)"
	TukuiL.option_datatext_power = "攻强/法伤(输入0关闭)"
	TukuiL.option_datatext_haste = "急速(输入0关闭)"
	TukuiL.option_datatext_friend = "好友(输入0关闭)"
	TukuiL.option_datatext_time = "时间(输入0关闭)"
	TukuiL.option_datatext_gold = "金币(输入0关闭)"
	TukuiL.option_datatext_dps = "DPS (输入0关闭)"
	TukuiL.option_datatext_crit = "爆击 % (输入0关闭)"
	TukuiL.option_datatext_dur = "耐久度(输入0关闭)"
	TukuiL.option_datatext_currency = "货币(输入0关闭)"
	TukuiL.option_datatext_micromenu = "微型菜单(输入0关闭)"
	TukuiL.option_datatext_hit = "命中(输入0关闭)"
	TukuiL.option_datatext_mastery = "精通 (输入0关闭)"
	TukuiL.option_datatext_regen = "Manaregeneration Position"
	TukuiL.option_datatext_calltoarms = "Call to Arms Position"
	TukuiL.option_datatext_profession = "Profession Position"
	TukuiL.option_datatext_block = "Block Position"
	TukuiL.option_datatext_dodge = "Dodge Position"
	TukuiL.option_datatext_parry = "Parry Position"

	-- unit frames
	TukuiL.option_unitframes_unitframes = "单位框体"
	TukuiL.option_unitframes_combatfeedback = "在玩家和目标框体上显示战斗信息"
	TukuiL.option_unitframes_runebar = "为死亡骑士启用符文条"
	TukuiL.option_unitframes_auratimer = "在光环上显示时间"
	TukuiL.option_unitframes_totembar = "为萨满启用图腾条"
	TukuiL.option_unitframes_totalhpmp = "显示总的生命/能量值"
	TukuiL.option_unitframes_playerparty = "在团队中显示你自己"
	TukuiL.option_unitframes_aurawatch = "启用PVE光环检测 (只能在GRIG模式下)"
	TukuiL.option_unitframes_castbar = "启用施法条"
	TukuiL.option_unitframes_targetaura = "启用目标光环"
	TukuiL.option_unitframes_saveperchar = "为每个角色单独存储框架位置"
	TukuiL.option_unitframes_playeraggro = "在自身头像上启用仇恨显示"
	TukuiL.option_unitframes_smooth = "启用平滑状态条"
	TukuiL.option_unitframes_portrait = "为自身和目标启用头像显示"
	TukuiL.option_unitframes_enable = "启用Tukui头像框架"
	TukuiL.option_unitframes_enemypower = "只显示敌对目标的能量值"
	TukuiL.option_unitframes_gridonly = "治疗模式下仅使用GRID样式"
	TukuiL.option_unitframes_healcomm = "启用预估治疗"
	TukuiL.option_unitframes_focusdebuff = "启用焦点DEBUFF"
	TukuiL.option_unitframes_raidaggro = "在小队/团队中启用仇恨显示"
	TukuiL.option_unitframes_boss = "启用BOSS框体"
	TukuiL.option_unitframes_enemyhostilitycolor = "用敌对颜色为敌人框体着色 (for PVP)"
	TukuiL.option_unitframes_hpvertical = "在Grid模式中垂直显示生命条"
	TukuiL.option_unitframes_symbol = "显示小队/团队标记"
	TukuiL.option_unitframes_threatbar = "启用仇恨条"
	TukuiL.option_unitframes_enablerange = "启用小队/团队距离检测"
	TukuiL.option_unitframes_focus = "启用焦点目标"
	TukuiL.option_unitframes_latency = "显示施法延时"
	TukuiL.option_unitframes_icon = "显示施法条图标"
	TukuiL.option_unitframes_playeraura = "为玩家启用额外的光环模式"
	TukuiL.option_unitframes_aurascale = "光环文字大小设置"
	TukuiL.option_unitframes_gridscale = "Grid框体大小"
	TukuiL.option_unitframes_manahigh = "法力值过高警报 (LR专用)"
	TukuiL.option_unitframes_manalow = "低法力值警报 (所有的法系职业)"
	TukuiL.option_unitframes_range = "小队/团队超出距离透明值"
	TukuiL.option_unitframes_maintank = "启用主坦克框架"
	TukuiL.option_unitframes_mainassist = "启用主助理框架"
	TukuiL.option_unitframes_unicolor = "启用单一的颜色主题(灰色的生命条)"
	TukuiL.option_unitframes_totdebuffs = "启用目标的目标的DEBUFF显示 (仅限高分辨率)"
	TukuiL.option_unitframes_classbar = "启用职业条（enable class bar)"
	TukuiL.option_unitframes_weakenedsoulbar = "启用灵魂虚弱指示 (MS)"
	TukuiL.option_unitframes_onlyselfdebuffs = "只在目标框体上显示你释放的DEBUFF"
	TukuiL.option_unitframes_focus = "启用焦点目标"
	TukuiL.option_unitframes_bordercolor = "设置为默认的边框颜色"
	TukuiL.option_unitframes_totdbsize = "Set size of Target of Target Debuffs"
	 
	-- loot
	TukuiL.option_loot = "拾取"
	TukuiL.option_loot_enableloot = "启用拾取框"
	TukuiL.option_loot_autogreed = "满级时启用自动贪婪绿色物品"
	TukuiL.option_loot_enableroll = "启用R点框体"
	 
	-- map
	TukuiL.option_map = "地图"
	TukuiL.option_map_enable = "启用Tukui风格的地图"
	TukuiL.option_map_bossicons = "Enable alternative Bossportraits on instancemaps"
	 
	-- invite
	TukuiL.option_invite = "邀请"
	TukuiL.option_invite_autoinvite = "开启自动接受邀请 (好友和公会成员)"
	 
	-- tooltip
	TukuiL.option_tooltip = "鼠标提示"
	TukuiL.option_tooltip_enable = "开启鼠标提示"
	TukuiL.option_tooltip_hidecombat = "战斗中关闭鼠标提示"
	TukuiL.option_tooltip_hidebutton = "关闭动作条按钮提示"
	TukuiL.option_tooltip_hideuf = "关闭单位框体的鼠标提示"
	TukuiL.option_tooltip_cursor = "启用提示跟随鼠标模式"
	TukuiL.option_tooltip_ilvl = "Display average itemlevel on tooltip"
	TukuiL.option_tooltip_showspellid = "Show SpellID on Tooltip"
	 
	-- others
	TukuiL.option_others = "其他"
	TukuiL.option_others_bg = "启用在战场中自动释放灵魂"
	 
	-- reminder
	TukuiL.option_reminder = "光环报警"
	TukuiL.option_reminder_enable = "启用玩家光环报警"
	TukuiL.option_reminder_sound = "为光环报警开启声音提示"
	 
	-- error
	TukuiL.option_error = "错误信息"
	TukuiL.option_error_hide = "隐藏屏幕中恼人的错误提示信息"
	 
	-- action bar
	TukuiL.option_actionbar = "动作条"
	TukuiL.option_actionbar_hidess = "隐藏姿态或者图腾栏"
	TukuiL.option_actionbar_showgrid = "始终在动作条上显示方格"
	TukuiL.option_actionbar_enable = "启用Tukui动作条"
	TukuiL.option_actionbar_rb = "启用右侧动作条鼠标划过显示"
	TukuiL.option_actionbar_hk = "显示热键名称"
	TukuiL.option_actionbar_ssmo = "鼠标划过显示姿态栏和图腾栏"
	TukuiL.option_actionbar_rbn = "底部动作条数目 (1 or 2)"
	TukuiL.option_actionbar_rn = "右侧动作条数目 (0, 1, 2 or 3)"
	TukuiL.option_actionbar_buttonsize = "主动作条按钮大小"
	TukuiL.option_actionbar_buttonspacing = "动作条按钮间距"
	TukuiL.option_actionbar_petbuttonsize = "宠物或姿态栏按钮大小"

	-- quest watch frame
	TukuiL.option_quest = "任务追踪"
	TukuiL.option_quest_movable = "可移动任务追踪"
	 
	-- arena
	TukuiL.option_arena = "竞技场"
	TukuiL.option_arena_st = "启用竞技场敌方施法监测"
	TukuiL.option_arena_uf = "启用竞技场单位框架"

	-- pvp
	TukuiL.option_pvp = "Pvp"
	TukuiL.option_pvp_ii = "启用打断图标"
	 
	-- cooldowns
	TukuiL.option_cooldown = "冷却"
	TukuiL.option_cooldown_enable = "在按钮上显示冷却时间"
	TukuiL.option_cooldown_th = "在X秒以后以红色显示冷却时间"
	 
	-- chat
	TukuiL.option_chat = "对话框"
	TukuiL.option_chat_enable = "启用Tukui的聊天框架"
	TukuiL.option_chat_whispersound = "在收到M语时播放提示音"
	TukuiL.option_chat_background = "启用聊天面板背景"

	-- buff
	TukuiL.option_auras = "光环"
	TukuiL.option_auras_player = "启用Tukui Buff/Debuff 框架"
	TukuiL.option_auras_consolidate = "Consolidate Buffs"
	TukuiL.option_auras_flash = "Flash Buffbutton"

	-- buttons
	TukuiL.option_button_reset = "重置"
	TukuiL.option_button_load = "应用设定"
	TukuiL.option_button_close = "关闭"
	TukuiL.option_setsavedsetttings = "为单一角色设定"
	TukuiL.option_resetchar = "你确定要重置角色的设置为默认值么?"
	TukuiL.option_resetall = "你确定重置所有的设定至默认值么?"
	TukuiL.option_perchar = "你确定要启用或者关闭“为单一角色设定”么?"
	TukuiL.option_makeselection = "在你继续设置之前你必须要做出一个选择"

end