TukuiL = { }

-- update needed msg
TukuiL.option_update = "You need to update your Tukui ConfigUI addon because of Tukui latest changes, please visit www.tukui.org"

--Duffed
TukuiL.option_general_blizzardsct = "Skin Blizzard SCT"
TukuiL.option_general_normalfont = "Use the Normal/Old Font instead of pixelfont."
TukuiL.option_general_overridehightolow = "Use Low-res Version on High-res"
TukuiL.option_general_bordercolor = "Bordercolor (Tukui Panels)"
TukuiL.option_general_backdropcolor = "Backdropcolor (Tukui Panels)"
TukuiL.option_general_classcolored_border = "Tukui-Panel-Border classcolored"

TukuiL.option_datatext_color = "Text Color (datatext, chat etc.)"
TukuiL.option_datatext_classcolored = "Classcolored Text"
TukuiL.option_datatext_zonepanel = "Panel that shows current Zone below Minimap"
TukuiL.option_datatext_experience = "Experience Position"
TukuiL.option_datatext_reputation = "Reputation Position"
TukuiL.option_datatext_mmenu = "mMenu Position (mMenu required)"
TukuiL.option_datatext_font = "Font (datatext, buffs, chat-tabs, ClassTimer)"
TukuiL.option_datatext_honorablekills = "Honorable Kills Position"
TukuiL.option_datatext_honor = "Honor Position"

TukuiL.option_unitframes_healthbarcolor = "Healthbar Color (unicolor)"
TukuiL.option_unitframes_deficitcolor = "Deficit Color (unicolor)"
TukuiL.option_unitframes_priestarmor = "Display current Armor for Priest"
TukuiL.option_unitframes_totandpetlines = "Display Lines from Pet & ToT"
TukuiL.option_unitframes_framewidth = "Player & Target width (affect also boss- & arenaframes)"
TukuiL.option_unitframes_fader = "[EXPERIMENTAL] Fade Unitframes out when not in combat (+ some more conditions ofc)"
TukuiL.option_unitframes_faderalpha = "(Fader) Alpha for frames (if not 0)"
TukuiL.option_unitframes_vengeancebar = "Display Vengeance-Bar instead of Threat-Bar"
TukuiL.option_unitframes_largefocus = "Use larger Focus Frame"
TukuiL.option_unitframes_gridvertical = "Grid direction vertical instead of horizontal"
TukuiL.option_unitframes_gridpets = "Show pets in Grid Layout (only in group, not raid)"
TukuiL.option_unitframes_fontsize = "Unitframe Fontsize"
TukuiL.option_unitframes_gridsolo = "Show Grid even without a Group (Solo)"
TukuiL.option_unitframes_focusdebuffs = "Enable Focus Debuffs"
TukuiL.option_unitframes_buffrows = "Buff-rows above Target"
TukuiL.option_unitframes_debuffrows = "Debuff-rows above Target"
TukuiL.option_unitframes_portraitstyle = "Portrait Style: ICON or MODEL (Layout 2 only)"
TukuiL.option_unitframes_layout = "Layout (1, 2, 3)"
TukuiL.option_unitframes_colorgradient = "Add Color-Gradient to healthbar (from red to healthbarcolor u set in config)"
TukuiL.option_unitframes_powerclasscolored = "Powerbar in class-color instead of power-color"
TukuiL.option_unitframes_outline = "Set Outline for Unitframes (NONE, OUTLINE, THINOUTLINE)"
TukuiL.option_unitframes_percent = "Show HP-Percent left an right of Player & Target"

TukuiL.option_castbar = "Castbar"
TukuiL.option_castbar_color = "Castbarcolor for not-player (if not classcolored)"
TukuiL.option_castbar_classcolored = "Castbar classcolored."
TukuiL.option_castbar_targetyoffset = "Target Castbar offset from the BOTTOM"
TukuiL.option_castbar_targetxoffset = "Target Castbar offset from the CENTER (horizontal)"
TukuiL.option_castbar_targetwidth = "Target Castbar width"
TukuiL.option_castbar_focusyoffset = "Focus Castbar offset from the TOP"
TukuiL.option_castbar_focusxoffset = "Focus Castbar offset from the CENTER (horizontal)"
TukuiL.option_castbar_focuswidth = "Focus Castbar width"

TukuiL.option_actionbar_swaprbar1and3 = "Swap Mainbar with 2. or 3. (depends on which AB-Layout you use)"
TukuiL.option_actionbar_rightbarsmouseover = "Rightbars on mouseover"
TukuiL.option_actionbar_shapeshiftborder = "Display Border around Shapeshiftbar"
TukuiL.option_actionbar_shapeshiftmouseover = "Shapeshiftbar on mouseover"
TukuiL.option_actionbar_shapeshiftvertical = "Set Shapeshiftbar vertical"
TukuiL.option_actionbar_macrotext = "Display Macrotext"
TukuiL.option_actionbar_macro = "Enable Macrohighlightning for Procs"
TukuiL.option_actionbar_petbaralwaysvisible = "Always show Petbar even if rightbarsmouseover = true"
TukuiL.option_actionbar_petbarhorizontal = "Petbar horizontal on top of Bar2/1"
TukuiL.option_actionbar_button2 = "Show or Hide the +/-Button at the bottom Datatextpanel"
TukuiL.option_actionbar_barlayout = "Set Actionbarlayout"
TukuiL.option_actionbar_panels = "Show or Hide the Actionbarpanels (only if you use an alternative Actionbarmod)"

TukuiL.option_duffed_drinkannouncement = "Announce 'drinking' in  Arena"
TukuiL.option_duffed_ccannouncement = "Announce CC/Buffs/Debuffs"
TukuiL.option_duffed_sayinterrupt = "Announce when you interrupt someone"
TukuiL.option_duffed_dispelannouncement = "Announce Dispels"
TukuiL.option_duffed_tbtimer = "Enable Tol Barad-Timer in watchframe"
TukuiL.option_duffed_priest_sos = "Enable display for Strength of Soul (Priests only)"
TukuiL.option_duffed_arenaonly = "Aura & Interrupt announcement in arena only."
TukuiL.option_duffed_announcechannel = "Set channel for Announcement (SAY, GROUP, RAID)"

TukuiL.option_classtimer = "Classtimer"
TukuiL.option_classtimer_enable = "Enable Classtimer"
TukuiL.option_classtimer_playercolor = "Player-Bar Color"
TukuiL.option_classtimer_targetbuffcolor = "Target-Buffs Color"
TukuiL.option_classtimer_targetdebuffcolor = "Target-Debuffs Color"
TukuiL.option_classtimer_trinketcolor = "Player-Trinket(Procs) Color"
TukuiL.option_classtimer_targetdebuffs = "Target Debuffs above Target (looks crappy imo :))"

TukuiL.option_chat_addonborder = "Create Panel that looks exactly like the left chat (by default) at the BOTTOMRIGHT"
TukuiL.option_chat_leftchatbackground = "Show Background for the left Chat (ChatFrame1)"
TukuiL.option_chat_rightchatbackground = "Show Background for the right Chat (ChatFrame4)"
TukuiL.option_chat_rightchatnumber = "Chat Number X (For Rightchat-Background)"
TukuiL.option_chat_fading = "Enable fading"
TukuiL.option_chat_rightchatalign = "Set textalign of right chat to left or right"

TukuiL.option_skins = "Skins"
TukuiL.option_skins_background = "Create Panel that looks exactly like the left chat (by default) at the BOTTOMRIGHT"
TukuiL.option_skins_combat_toggle = "Toggle Addonbackground in-/outfight (NOTE: Turn off auto-hide functions in these Addons)"
TukuiL.option_skins_bskins = "Enable Skinning for Blizzardframes"
TukuiL.option_skins_itemborder =  "Enable Qualityborder for Items on Character / Inspectframe"

TukuiL.option_misc = "Misc Options"
TukuiL.option_misc_swingtimerenable = "Enable SwingTimer"
TukuiL.option_misc_swingtimerwidth = "Swingtimer Width"
TukuiL.option_misc_swingtimerheight = "Swingtimer Height"
TukuiL.option_misc_swingtimercolor = "Swingtimer Bar-Color"
TukuiL.option_misc_sesenable = "Enable Specswitcher"
TukuiL.option_misc_sesenablegear = "Enable automatic gearswap"
TukuiL.option_misc_sesset1 = "Equipset for first spec (must be a number between 1 - 10)"
TukuiL.option_misc_sesset2 = "Equipset for second spec (must be a number between 1 - 10)"
TukuiL.option_misc_sesgearswap = "Enable automatic gearswap for respec"
TukuiL.option_misc_sescastbar = "Enable castbar for specswitcher"
TukuiL.option_misc_rbf = "Enable RaidBuff Reminder"
TukuiL.option_misc_rbfmouseover = "Enable mouseover for RaidBuff Reminder"
TukuiL.option_misc_rbfvertical = "Set RaidBuff Reminder vertical"
TukuiL.option_nameplate_debuff =  "Enable Debuffdisplay on nameplates"
TukuiL.option_misc_tbchattab = "Set Threatbarpoint to ChatBG2Tab"
TukuiL.option_misc_sComboenable = "Enable sCombo-Addon for combopoints instead of default cp-display"
TukuiL.option_misc_sComboenergybar = "Show Energy-Bar below Combopoints"

-- general
TukuiL.option_general = "General"
TukuiL.option_general_uiscale = "Auto UI Scale"
TukuiL.option_general_override = "Use High resolution  layout on a Lower resolution"
TukuiL.option_general_multisample = "Multisampling protection (clean 1px border)"
TukuiL.option_general_customuiscale = "UI Scale (if auto-scale is disabled)"

-- nameplate
TukuiL.option_nameplates = "Nameplates"
TukuiL.option_nameplates_enable = "Enable Nameplates"
TukuiL.option_nameplates_enhancethreat = "Enable threat feature, automatically changes by your role"
TukuiL.option_nameplates_showhealth = "Show health on nameplate"
TukuiL.option_nameplates_combat = "Only show enemy nameplates in-combat"
TukuiL.option_nameplates_goodcolor = "Good threat color, varies depending if your a tank or dps/heal"
TukuiL.option_nameplates_badcolor = "Bad threat color, varies depending if your a tank or dps/heal"
TukuiL.option_nameplates_transitioncolor = "Losing/Gaining threat color"
 
-- merchant
TukuiL.option_merchant = "Merchant"
TukuiL.option_merchant_autosell = "Auto sell grey items"
TukuiL.option_merchant_autorepair = "Auto Repair items"
TukuiL.option_merchant_sellmisc = "Sell some defined (craps not grey) items automatically"
TukuiL.option_merchant_autoguildrepair = "Autorepair from Guild Bank if possible."
 
-- bags
TukuiL.option_bags = "Bags"
TukuiL.option_bags_enable = "Enable all-in-one bag"
TukuiL.option_bags_moveable = "Enable to move your bags"
TukuiL.option_bags_transparent = "Enable Transparent for bags"
 
-- datatext
TukuiL.option_datatext = "Data Text"
TukuiL.option_datatext_24h = "Enable 24h time"
TukuiL.option_datatext_localtime = "Use Local Time instead of Server Time"
TukuiL.option_datatext_bg = "Enable Battleground Stats"
TukuiL.option_datatext_hps = "Healing per second, position (0 for disabled)"
TukuiL.option_datatext_guild = "Guild position (0 for disabled)"
TukuiL.option_datatext_arp = "Armor penetration position (0 for disabled)"
TukuiL.option_datatext_mem = "Memory position (0 for disabled)"
TukuiL.option_datatext_bags = "Bags position (0 for disabled)"
TukuiL.option_datatext_fontsize = "Font size of text"
TukuiL.option_datatext_fps_ms = "Latency and FPS position (0 for disabled)"
TukuiL.option_datatext_armor = "Armor Position (0 for disabled)"
TukuiL.option_datatext_avd = "Avoidance position (0 for disabled)"
TukuiL.option_datatext_power = "Power position (0 for disabled)"
TukuiL.option_datatext_haste = "Haste position (0 for disabled)"
TukuiL.option_datatext_friend = "Friends position (0 for disabled)"
TukuiL.option_datatext_time = "Time position (0 for disabled)"
TukuiL.option_datatext_gold = "Gold position (0 for disabled)"
TukuiL.option_datatext_dps = "Damage per second position (0 for disabled)"
TukuiL.option_datatext_crit = "Crit % position (0 for disabled)"
TukuiL.option_datatext_dur = "Durability position (0 for disabled)"
TukuiL.option_datatext_currency = "Currency position (0 for disabled)"
TukuiL.option_datatext_micromenu = "Micro Menu position (0 for disabled)"
TukuiL.option_datatext_hit = "Hit position (0 for disabled)"
TukuiL.option_datatext_mastery = "Mastery position (0 for disabled)"
TukuiL.option_datatext_regen = "Manaregeneration Position"
TukuiL.option_datatext_calltoarms = "Call to Arms Position"
TukuiL.option_datatext_profession = "Profession Position"
TukuiL.option_datatext_block = "Block Position"
TukuiL.option_datatext_dodge = "Dodge Position"
TukuiL.option_datatext_parry = "Parry Position"
 
-- unit frames
TukuiL.option_unitframes_unitframes = "Unit Frames"
TukuiL.option_unitframes_combatfeedback = "Combat Feedback on player and target"
TukuiL.option_unitframes_runebar = "Enable rune bar for Death Knight"
TukuiL.option_unitframes_auratimer = "Enable timer on auras"
TukuiL.option_unitframes_totembar = "Enable totem bar for Shaman"
TukuiL.option_unitframes_totalhpmp = "Display total of health/power"
TukuiL.option_unitframes_playerparty = "Show yourself in party"
TukuiL.option_unitframes_aurawatch = "Enable PVE raid Aura Watch (Grid Only)"
TukuiL.option_unitframes_castbar = "Enable cast bar"
TukuiL.option_unitframes_targetaura = "Enable target auras"
TukuiL.option_unitframes_saveperchar = "Save unit frames position per character"
TukuiL.option_unitframes_playeraggro = "Enable aggro display on yourself"
TukuiL.option_unitframes_smooth = "Enable smooth bar"
TukuiL.option_unitframes_portrait = "Enable portraits on player and target"
TukuiL.option_unitframes_enable = "Enable Tukui Unit Frames"
TukuiL.option_unitframes_enemypower = "Enable Power display on enemy only"
TukuiL.option_unitframes_gridonly = "Enable Grid only mode for Healer layout"
TukuiL.option_unitframes_healcomm = "Enable healcomm"
TukuiL.option_unitframes_focusdebuff = "Enable Focus debuffs"
TukuiL.option_unitframes_raidaggro = "Enable aggro display on party/raid"
TukuiL.option_unitframes_boss = "Enable Boss Unit Frames"
TukuiL.option_unitframes_enemyhostilitycolor = "Color enemy health bar by hostility (for PVP)"
TukuiL.option_unitframes_hpvertical = "Show health bar vertically for Grid layout"
TukuiL.option_unitframes_symbol = "Show symbols on party/raid"
TukuiL.option_unitframes_threatbar = "Enable threat bar"
TukuiL.option_unitframes_enablerange = "Enable party/raid Range alpha display"
TukuiL.option_unitframes_focus = "Enable Focus target"
TukuiL.option_unitframes_latency = "Show cast bar latency"
TukuiL.option_unitframes_icon = "Show icons on cast bar"
TukuiL.option_unitframes_playeraura = "Enable an alternative aura mode for player"
TukuiL.option_unitframes_aurascale = "Aura text scale on auras"
TukuiL.option_unitframes_gridscale = "Grid Scale"
TukuiL.option_unitframes_manahigh = "High mana indicator (For Hunters)"
TukuiL.option_unitframes_manalow = "Low mana indicator (All mana class)"
TukuiL.option_unitframes_range = "Alpha on Party/Raid unit out of range"
TukuiL.option_unitframes_maintank = "Enable Main Tank"
TukuiL.option_unitframes_mainassist = "Enable Main Assist"
TukuiL.option_unitframes_unicolor = "Enable Unique color theme (grey health bar)"
TukuiL.option_unitframes_totdebuffs = "Enable Target of Target debuffs (High Reso)"
TukuiL.option_unitframes_classbar = "Enable class bar"
TukuiL.option_unitframes_weakenedsoulbar = "Enable Weakened Soul bar notification (Priest)"
TukuiL.option_unitframes_onlyselfdebuffs = "Display only our debuffs on target"
TukuiL.option_unitframes_focus = "Enable Focus target"
TukuiL.option_unitframes_totdbsize = "Set size of Target of Target Debuffs"
 
-- loot
TukuiL.option_loot = "Loot"
TukuiL.option_loot_enableloot = "Enable loot window"
TukuiL.option_loot_autogreed = "Enable auto-greed for green item at max level"
TukuiL.option_loot_enableroll = "Enable item roll window"
 
-- map
TukuiL.option_map = "Map"
TukuiL.option_map_enable = "Enable Map"
TukuiL.option_map_bossicons = "Enable alternative Bossportraits on instancemaps"

-- invite
TukuiL.option_invite = "Invite"
TukuiL.option_invite_autoinvite = "Enable Auto-Invite (Friends and Guildmates)"
 
-- tooltip
TukuiL.option_tooltip = "Tooltip"
TukuiL.option_tooltip_enable = "Enable tooltip"
TukuiL.option_tooltip_hidecombat = "Hide tooltip in combat"
TukuiL.option_tooltip_hidebutton = "Hide tooltip on action bar buttons"
TukuiL.option_tooltip_hideuf = "Hide tooltip on unit frames"
TukuiL.option_tooltip_cursor = "Enable cursor tooltip"
TukuiL.option_tooltip_ilvl = "Display average itemlevel on tooltip"
TukuiL.option_tooltip_showspellid = "Show SpellID on Tooltip"
 
-- others
TukuiL.option_others = "Others"
TukuiL.option_others_bg = "Enable Auto-Release in battlegrounds"
 
-- reminder
TukuiL.option_reminder = "Aura Warning"
TukuiL.option_reminder_enable = "Enable player aura warning"
TukuiL.option_reminder_sound = "Enable a warning sound for aura warning"
 
-- error
TukuiL.option_error = "Error Message"
TukuiL.option_error_hide = "Hide spamming error in the middle of your screen"
 
-- action bar
TukuiL.option_actionbar = "Action Bars"
TukuiL.option_actionbar_hidess = "Hide Shapeshift bar or Totem bar"
TukuiL.option_actionbar_showgrid = "Always show Grid on action bar"
TukuiL.option_actionbar_enable = "Enable Tukui action bar"
TukuiL.option_actionbar_rb = "Enable right bar on mouseover"
TukuiL.option_actionbar_hk = "Show hotkey on buttons"
TukuiL.option_actionbar_ssmo = "Shapeshift bar or Totem bar on mouseover"
TukuiL.option_actionbar_rbn = "Number of action bars on the bottom (1 or 2)"
TukuiL.option_actionbar_rn = "Number of action bars on right (0, 1, 2 or 3)"
TukuiL.option_actionbar_buttonsize = "Size of the main action buttons"
TukuiL.option_actionbar_buttonspacing = "Spacing of the main action buttons"
TukuiL.option_actionbar_petbuttonsize = "Size of pet/shapeshift buttons"

-- quest watch frame
TukuiL.option_quest = "Quests"
TukuiL.option_quest_movable = "Quest Watch frame movable"
 
-- arena
TukuiL.option_arena = "Arena"
TukuiL.option_arena_st = "Enable enemy spell tracker in arena"
TukuiL.option_arena_uf = "Enable arena unit frames"

-- pvp
TukuiL.option_pvp = "Pvp"
TukuiL.option_pvp_ii = "Enable Interrupt Icons"
 
-- cooldowns
TukuiL.option_cooldown = "Cooldowns"
TukuiL.option_cooldown_enable = "Enable cooldown number on buttons"
TukuiL.option_cooldown_th = "Turn cooldown number red at X value"
 
-- chat
TukuiL.option_chat = "Social"
TukuiL.option_chat_enable = "Enable Tukui Chat"
TukuiL.option_chat_whispersound = "Play sound when receiving private message"
TukuiL.option_chat_background = "Enable chat panel background"

-- buff
TukuiL.option_auras = "Auras"
TukuiL.option_auras_player = "Enable Tukui Buff/Debuff Frames"
TukuiL.option_auras_consolidate = "Consolidate Buffs"
TukuiL.option_auras_flash = "Flash Buffbutton"

-- buttons
TukuiL.option_button_reset = "Reset"
TukuiL.option_button_load = "Apply Settings"
TukuiL.option_button_close = "Close"
TukuiL.option_setsavedsetttings = "Set settings Per-Character"
TukuiL.option_resetchar = "Are you sure you want to reset your character's settings to match your default settings?"
TukuiL.option_resetall = "Are you sure you want to reset all of your settings to Default?"
TukuiL.option_perchar = "Are you sure you want to change to or from 'Per Char Settings'?"
TukuiL.option_makeselection = "You must make a selection before you can continue to config."